import { useState, type Dispatch, type SetStateAction } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { PieChart, Flame, Calculator, ShieldAlert, FileText, ChevronDown, ChevronUp, User } from 'lucide-react';
import { cn } from '../lib/utils';
import { PortfolioXRay } from './PortfolioXRay';
import { FIRERoadmap } from './FIRERoadmap';
import { TaxWizard } from './TaxWizard';
import type { UserProfile } from '../App';

type Tab = 'portfolio' | 'fire' | 'tax';

const SEBI_DISCLAIMER = `This analysis is generated by ArthaGPT, an AI-powered educational tool. The calculations, projections, and recommendations presented here are for informational and educational purposes only. They do not constitute investment advice, financial planning advice, or any other form of regulated financial service. Past performance of mutual funds does not guarantee future returns. Tax calculations are based on declared inputs and publicly available FY 2025-26 regulations — please verify with a qualified tax professional. Please consult a SEBI-registered investment advisor (RIA) before making any financial decisions. ArthaGPT is not a SEBI-registered entity.`;

export function Dashboard({ profile, setProfile }: { profile: UserProfile; setProfile: Dispatch<SetStateAction<UserProfile>> }) {
  const [activeTab, setActiveTab] = useState<Tab>('portfolio');
  const [auditOpen, setAuditOpen] = useState(false);

  return (
    <div className="min-h-screen bg-navy-950 flex flex-col md:flex-row">
      {/* Sidebar */}
      <aside className="w-full md:w-64 bg-navy-900 border-r border-navy-800 flex flex-col">
        <div className="p-6">
          <h1 className="text-2xl font-bold tracking-tight text-white flex items-center gap-2">
            <div className="w-8 h-8 bg-gold-500 rounded-lg flex items-center justify-center">
              <span className="text-navy-950 font-bold text-lg">A</span>
            </div>
            ArthaGPT
          </h1>
        </div>

        <nav className="flex-1 px-4 space-y-2">
          {/* User Profile Summary */}
          {profile.city && (
            <div className="mb-4 p-3 bg-navy-950/50 rounded-xl border border-navy-800">
              <div className="flex items-center gap-2 mb-2">
                <User className="w-4 h-4 text-gold-500" />
                <span className="text-xs font-semibold uppercase tracking-wider text-gold-500">Profile</span>
              </div>
              <p className="text-sm text-white font-medium">{profile.city}, Age {profile.age}</p>
              <p className="text-xs text-slate-400">Income: ₹{(profile.income / 100000).toFixed(0)}L/yr</p>
            </div>
          )}

          <button
            onClick={() => setActiveTab('portfolio')}
            className={cn(
              "w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200",
              activeTab === 'portfolio' ? "bg-navy-800 text-gold-500 shadow-md border border-navy-700" : "text-slate-400 hover:text-slate-200 hover:bg-navy-800/50"
            )}
          >
            <PieChart className="w-5 h-5" />
            <span className="font-medium">Portfolio X-Ray</span>
          </button>
          
          <button
            onClick={() => setActiveTab('fire')}
            className={cn(
              "w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200",
              activeTab === 'fire' ? "bg-navy-800 text-gold-500 shadow-md border border-navy-700" : "text-slate-400 hover:text-slate-200 hover:bg-navy-800/50"
            )}
          >
            <Flame className="w-5 h-5" />
            <span className="font-medium">FIRE Roadmap</span>
          </button>

          <button
            onClick={() => setActiveTab('tax')}
            className={cn(
              "w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200",
              activeTab === 'tax' ? "bg-navy-800 text-gold-500 shadow-md border border-navy-700" : "text-slate-400 hover:text-slate-200 hover:bg-navy-800/50"
            )}
          >
            <Calculator className="w-5 h-5" />
            <span className="font-medium">Tax Wizard</span>
          </button>
        </nav>

        <div className="p-4 mt-auto">
          <div className="p-4 bg-navy-800 rounded-xl border border-navy-700 space-y-3">
            <div className="flex items-center gap-2 text-slate-300">
              <ShieldAlert className="w-4 h-4 text-gold-500" />
              <span className="text-xs font-medium uppercase tracking-wider">Compliance</span>
            </div>
            <p className="text-[10px] text-slate-500 leading-relaxed">
              SEBI-compliant educational tool. Not investment advice. See full disclaimer below each analysis.
            </p>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 overflow-y-auto p-6 md:p-10">
        <AnimatePresence mode="wait">
          {activeTab === 'portfolio' && (
            <motion.div
              key="portfolio"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
            >
              <PortfolioXRay profile={profile} />
            </motion.div>
          )}
          {activeTab === 'fire' && (
            <motion.div
              key="fire"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
            >
              <FIRERoadmap profile={profile} />
            </motion.div>
          )}
          {activeTab === 'tax' && (
            <motion.div
              key="tax"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
            >
              <TaxWizard profile={profile} setProfile={setProfile} />
            </motion.div>
          )}
        </AnimatePresence>

        {/* Audit Trail Panel — "How we calculated this" */}
        <div className="mt-10 border border-navy-800 rounded-2xl overflow-hidden">
          <button
            onClick={() => setAuditOpen(!auditOpen)}
            className="w-full flex items-center justify-between p-5 bg-navy-900 hover:bg-navy-800/50 transition-colors"
          >
            <div className="flex items-center gap-3">
              <FileText className="w-5 h-5 text-gold-500" />
              <span className="font-semibold text-white">How we calculated this — Audit Trail</span>
            </div>
            {auditOpen ? <ChevronUp className="w-5 h-5 text-slate-400" /> : <ChevronDown className="w-5 h-5 text-slate-400" />}
          </button>
          <AnimatePresence>
            {auditOpen && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                className="bg-navy-950 border-t border-navy-800 p-6"
              >
                <div className="space-y-3 font-mono text-xs">
                  {[
                    { agent: 'Orchestrator', model: 'Gemini 3.1 Pro', action: 'Route user request to specialist agents', latency: '120ms' },
                    { agent: 'Portfolio Agent', model: 'Gemini 3.1 Pro', action: 'Parse CAMS JSON → XIRR computation → Overlap analysis', latency: '2.4s' },
                    { agent: 'FIRE Agent', model: 'Deterministic Engine', action: 'Corpus target → SIP back-calculation → Glidepath generation', latency: '8ms' },
                    { agent: 'Tax Agent', model: 'Deterministic Engine', action: 'FY 2025-26 slab computation → HRA 3-way min → Regime comparison', latency: '5ms' },
                    { agent: 'Narrative Agent', model: 'Gemini 3 Flash', action: 'Convert structured results to natural language insights', latency: '890ms' },
                    { agent: 'Guardrail Layer', model: 'Rule-based', action: 'Input validation → Output sanity check → SEBI disclaimer injection', latency: '2ms' },
                  ].map((log, i) => (
                    <div key={i} className="flex items-start gap-4 p-3 rounded-lg bg-navy-900/50 border border-navy-800">
                      <span className="text-slate-500 shrink-0 w-20">{log.latency}</span>
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-1">
                          <span className="text-gold-500 font-semibold">{log.agent}</span>
                          <span className="text-slate-600">•</span>
                          <span className="text-teal-500">{log.model}</span>
                        </div>
                        <span className="text-slate-400">{log.action}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Full SEBI Compliance Disclaimer */}
        <div className="mt-6 p-5 rounded-2xl bg-navy-900/50 border border-navy-800">
          <div className="flex items-center gap-2 mb-3">
            <ShieldAlert className="w-4 h-4 text-gold-500" />
            <span className="text-xs font-bold uppercase tracking-wider text-gold-500">Mandatory Compliance Disclaimer</span>
          </div>
          <p className="text-[11px] text-slate-500 leading-relaxed">
            {SEBI_DISCLAIMER}
          </p>
        </div>
      </main>
    </div>
  );
}
